export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const LOAD_ITEMS = 'LOAD_ITEMS'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const SUB_QUANTITY = 'SUB_QUANTITY'
    // export const LOAD_TOTAL = 'LOAD_TOTAL'